<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WL361561" failures="0" tests="3" name="com.tieto.test.LoginTest" time="25.198" errors="1" timestamp="2020-07-03T14:50:46 IST" skipped="0">
  <testcase classname="com.tieto.test.LoginTest" name="checkLinkCountTest" time="10.447"/>
  <system-out/>
  <testcase classname="com.tieto.test.LoginTest" name="validCredentialTest" time="14.751"/>
  <system-out/>
  <testcase classname="com.tieto.test.LoginTest" name="invalidCredentialTest" time="0.000">
    <error message="
Method public void com.tieto.test.LoginTest.invalidCredentialTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : invalidCredentialData" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method public void com.tieto.test.LoginTest.invalidCredentialTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : invalidCredentialData
at org.testng.internal.Parameters.findDataProvider(Parameters.java:563)
at org.testng.internal.Parameters.handleParameters(Parameters.java:776)
at org.testng.internal.Parameters.handleParameters(Parameters.java:744)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:783)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- invalidCredentialTest -->
  <system-out/>
</testsuite> <!-- com.tieto.test.LoginTest -->
